

/**
 * Standard issue-label set, with their resolved colors and human-readable
 * descriptions. The array is the only thing you need; `Label`describes a row.
 *
 * @summary 286-label issue taxonomy with sRGB colors and descriptions
 * @category labels
 *
 * @example
 * ```ts
 * import { labels, type Label } from 'issue_labels';
 *
 * const bugs: readonly Label[] = labels.filter(l => l.name === 'Bug');
 * console.log(bugs[0]?.color);  //=> "#ff3f00"
 * ```
 *
 * @since 0.3.0
 * @author John Haugeland
 *
 * @privateRemarks
 * Generated from src/data/standard_issue_label.json by
 * src/build_js/export_labels_ts.cjs (`npm run export:labels`). To regenerate
 * after the visualizer sim and bake step update label colors, re-run that
 * script -- it rewrites only the data rows, leaving this header intact. The
 * array is frozen-by-type (readonly) so consumers can't mutate it accidentally.
 */

export interface Label {
  readonly name        : string;
  readonly color       : string;
  readonly description : string;
}

export const labels: readonly Label[] = [
  { name: "Bug", color: "#ff3f00", description: "A defect or behavior that does not work as intended." },
  { name: "Refactor", color: "#ae11ff", description: "Restructuring existing code without changing its behavior." },
  { name: "Build", color: "#00fd1f", description: "Concerns the build pipeline, bundling, or compiled output." },
  { name: "New icon", color: "#b1a1c0", description: "A request to add a new icon to the set." },
  { name: "Font pipeline", color: "#384eee", description: "Concerns the font generation and assembly pipeline." },
  { name: "Variable axis", color: "#3c63f3", description: "Relates to variable-font axis behavior (fvar/gvar)." },
  { name: "Color", color: "#3358ff", description: "Relates to COLR/CPAL color handling in the font." },
  { name: "Composition", color: "#4452ff", description: "Relates to composing glyphs from other glyphs." },
  { name: "Rendering compatibility", color: "#c098ba", description: "Cross-browser or cross-platform rendering differences." },
  { name: "Frontend", color: "#ffa2b7", description: "Concerns the React frontend rather than the font engine." },
  { name: "Is blocked", color: "#00a5c3", description: "Cannot progress until another issue or dependency clears." },
  { name: "Good first issue", color: "#39c6ff", description: "Well-scoped and approachable for new contributors." },
  { name: "Help wanted", color: "#ff9b14", description: "Maintainers are actively seeking outside help." },
  { name: "Created by AI", color: "#9932cc", description: "Issue opened by an AI assistant." },
  { name: "Closed by AI", color: "#8b008b", description: "Issue closed by an AI assistant." },
  { name: "Difficulty: easy", color: "#49d1ff", description: "Straightforward work needing little effort or context." },
  { name: "Difficulty: medium", color: "#4abeff", description: "Moderate effort or domain knowledge required." },
  { name: "Difficulty: difficult", color: "#4cabff", description: "Substantial effort, complexity, or expertise required." },
  { name: "Needs research", color: "#6b7900", description: "Requires investigation before it can be acted on." },
  { name: "List issue", color: "#0dffe9", description: "A tracking issue that aggregates other work items." },
  { name: "Package Quality", color: "#79eccb", description: "Concerns the npm package listing, metadata, or score." },
  { name: "Needs a feature", color: "#658d00", description: "Blocked pending a feature that does not yet exist." },
  { name: "Suppressed", color: "#9aff92", description: "Deliberately set aside and hidden from normal triage." },
  { name: "Temporary solution proposed", color: "#002767", description: "A stopgap workaround has been suggested." },
  { name: "Solution proposed", color: "#003573", description: "A proper fix or approach has been suggested." },
  { name: "Core", color: "#ecb7a6", description: "Concerns the core library rather than peripheral parts." },
  { name: "Extension", color: "#ff9f97", description: "Concerns an optional extension or add-on." },
  { name: "Dependencies", color: "#8fee2e", description: "Relates to third-party dependencies or their updates." },
  { name: "Duplicate", color: "#c70051", description: "Already reported in another issue." },
  { name: "Enhancement", color: "#a400ff", description: "An improvement to existing functionality." },
  { name: "Javascript", color: "#f7df1e", description: "Relates to JavaScript code." },
  { name: "Typescript", color: "#3178c6", description: "Relates to TypeScript code." },
  { name: "Process", color: "#21ffe3", description: "Relates to project process, workflow, or governance." },
  { name: "Question", color: "#d8004a", description: "A question rather than an actionable defect or request." },
  { name: "Automation", color: "#7eff3f", description: "Relates to automation, CI, or scripted workflows." },
  { name: "CDN", color: "#84ff2b", description: "Relates to content-delivery-network hosting or distribution." },
  { name: "Chore", color: "#dd00c7", description: "General routine work that simply needs to get done." },
  { name: "Cleanup", color: "#ef00c2", description: "Tidying code, files, or configuration." },
  { name: "Competition", color: "#b87d14", description: "Comparison with or response to competing projects." },
  { name: "Compile targets", color: "#00ef2b", description: "Concerns the supported compilation or output targets." },
  { name: "Erlang", color: "#a90533", description: "Relates to Erlang code." },
  { name: "CSS", color: "#1572b6", description: "Relates to CSS styling." },
  { name: "HTML", color: "#e34f26", description: "Relates to HTML markup." },
  { name: "C", color: "#a8b9cc", description: "Relates to C code." },
  { name: "C++", color: "#00599c", description: "Relates to C++ code." },
  { name: "PHP", color: "#777bc0", description: "Relates to PHP code." },
  { name: "Java", color: "#ed8b00", description: "Relates to Java code." },
  { name: "Python", color: "#3776ab", description: "Relates to Python code." },
  { name: "D", color: "#b03931", description: "Relates to D code." },
  { name: "Ruby", color: "#cc342d", description: "Relates to Ruby code." },
  { name: "Ease of contribution", color: "#5cb6ff", description: "Concerns how approachable the project is to contributors." },
  { name: "C#", color: "#9b3f96", description: "Relates to C# code." },
  { name: "Go", color: "#00add8", description: "Relates to Go code." },
  { name: "Swift", color: "#fa7343", description: "Relates to Swift code." },
  { name: ".NET", color: "#512bd4", description: "Relates to the .NET platform." },
  { name: "Perl", color: "#39457e", description: "Relates to Perl code." },
  { name: "Kotlin", color: "#7f52ff", description: "Relates to Kotlin code." },
  { name: "SQL", color: "#833800", description: "Relates to SQL code." },
  { name: "Rust", color: "#ce422b", description: "Relates to Rust code." },
  { name: "R", color: "#198ce7", description: "Relates to R code." },
  { name: "Dart", color: "#0175c2", description: "Relates to Dart code." },
  { name: "Lua", color: "#000080", description: "Relates to Lua code." },
  { name: "ASP", color: "#763c7f", description: "Relates to ASP / Active Server Pages code." },
  { name: "Scala", color: "#dc322f", description: "Relates to Scala code." },
  { name: "Elixir", color: "#4b275f", description: "Relates to Elixir code." },
  { name: "Delphi/Object Pascal", color: "#e33910", description: "Relates to Delphi or Object Pascal code." },
  { name: "Visual Basic", color: "#945dc0", description: "Relates to Visual Basic code." },
  { name: "Assembly", color: "#8cc084", description: "Relates to assembly code." },
  { name: "Matlab", color: "#0076a8", description: "Relates to MATLAB code." },
  { name: "Objective-C", color: "#438eff", description: "Relates to Objective-C code." },
  { name: "PL/SQL", color: "#8a2600", description: "Relates to PL/SQL code." },
  { name: "MySQL DDL", color: "#00758f", description: "Relates to MySQL data-definition-language code." },
  { name: "COBOL", color: "#2c68a5", description: "Relates to COBOL code." },
  { name: "ABAP", color: "#0faaff", description: "Relates to ABAP code." },
  { name: "T-SQL", color: "#cc2927", description: "Relates to Transact-SQL code." },
  { name: "LISP", color: "#4e007d", description: "Relates to Lisp code." },
  { name: "Scheme", color: "#3c0078", description: "Relates to Scheme code." },
  { name: "Prolog", color: "#17c57e", description: "Relates to Prolog code." },
  { name: "Ada", color: "#02f88c", description: "Relates to Ada code." },
  { name: "Apex", color: "#1798c1", description: "Relates to Apex code." },
  { name: "Fortran", color: "#8b84c0", description: "Relates to Fortran code." },
  { name: "Haskell", color: "#5d3f85", description: "Relates to Haskell code." },
  { name: "Hack", color: "#71653f", description: "Relates to Hack code." },
  { name: "BASH", color: "#4eaa25", description: "Relates to Bash shell scripts." },
  { name: "Solidity", color: "#363636", description: "Relates to Solidity code." },
  { name: "Powershell", color: "#5391fe", description: "Relates to PowerShell scripts." },
  { name: "APL", color: "#13bc6d", description: "Relates to APL code." },
  { name: "Clojure", color: "#5881d8", description: "Relates to Clojure code." },
  { name: "Zig", color: "#f7a41d", description: "Relates to Zig code." },
  { name: "Batch file", color: "#003497", description: "Relates to Windows batch-file scripts." },
  { name: "Unity script", color: "#25c46e", description: "Relates to Unity scripting." },
  { name: "FSL", color: "#12d06c", description: "Relates to FSL (Finite State Language) code." },
  { name: "Julia", color: "#a270c0", description: "Relates to Julia code." },
  { name: "Groovy", color: "#3f98b8", description: "Relates to Groovy code." },
  { name: "F#", color: "#378bba", description: "Relates to F# code." },
  { name: "OCaml", color: "#ee6a1f", description: "Relates to OCaml code." },
  { name: "Markdown", color: "#000000", description: "Relates to Markdown content." },
  { name: "Racket", color: "#3c5caa", description: "Relates to Racket code." },
  { name: "Forth", color: "#21d579", description: "Relates to Forth code." },
  { name: "Documentation and docgen", color: "#5bff6e", description: "Relates to documentation or its generation." },
  { name: "Editors", color: "#ff4ffd", description: "Relates to editor or IDE integration." },
  { name: "Examples", color: "#ffd7e9", description: "Example usage of the project." },
  { name: "Features", color: "#b800ff", description: "Relates to the project's feature set." },
  { name: "Use cases", color: "#ffe3d8", description: "Documents or explores real-world use cases." },
  { name: "Icons", color: "#b8afc0", description: "Relates to the icon set or specific icons." },
  { name: "Issue needs work", color: "#5a02d1", description: "The issue report itself needs more detail or clarity; problem may still be real." },
  { name: "Low hanging fruit", color: "#3bb3ff", description: "A quick, low-effort win." },
  { name: "Low priority", color: "#c253bd", description: "Can be deferred; not urgent." },
  { name: "High priority", color: "#c768bf", description: "Important; should be addressed soon." },
  { name: "Machine exposition", color: "#57ff82", description: "Machine-readable explanation or generated exposition." },
  { name: "Needs tests", color: "#8f5dff", description: "Requires test coverage before it can be completed." },
  { name: "Environments", color: "#89ee41", description: "Relates to runtime or development environments." },
  { name: "Package managers", color: "#90ff39", description: "Relates to package-manager support or distribution." },
  { name: "Performance", color: "#5ffdcf", description: "Concerns execution speed or resource usage." },
  { name: "Size improvement", color: "#6aeed8", description: "Reducing bundle, file, or footprint size." },
  { name: "Publicity and visibility", color: "#c0654d", description: "Improving the project's visibility and reach." },
  { name: "Readme", color: "#48ff74", description: "Relates to the README file." },
  { name: "REPL", color: "#ff36ef", description: "Relates to an interactive REPL or playground." },
  { name: "Intend to close", color: "#9dff7d", description: "Slated for closure unless objections are raised." },
  { name: "Stochastics", color: "#7d54ff", description: "Relates to stochastic or property-based testing." },
  { name: "Tooling", color: "#ff29e7", description: "Relates to development tooling and build scripts." },
  { name: "Tutorials", color: "#ffeceb", description: "Step-by-step tutorial content." },
  { name: "Types", color: "#ff50e7", description: "Relates to type definitions or the type system." },
  { name: "Very powerful", color: "#d9d45a", description: "Highlights a notably powerful capability." },
  { name: "Visual improvements", color: "#73ffd2", description: "Improvements to visual appearance or design." },
  { name: "Visualizations", color: "#ff2afd", description: "Relates to data or bundle visualizations." },
  { name: "Widgets", color: "#ed969e", description: "Relates to UI widgets." },
  { name: "Windows", color: "#0078d6", description: "Relates to the Windows platform." },
  { name: "Mac", color: "#c0a6a6", description: "Relates to the macOS platform." },
  { name: "iOS", color: "#007aff", description: "Relates to the iOS platform." },
  { name: "Android", color: "#3ddc84", description: "Relates to the Android platform." },
  { name: "Linux", color: "#fcc624", description: "Relates to the Linux platform." },
  { name: "Web", color: "#6d8f3f", description: "Relates to the web platform and browsers." },
  { name: "Unity", color: "#222c37", description: "Relates to the Unity engine as a target platform." },
  { name: "Playstation", color: "#003791", description: "Relates to the PlayStation platform." },
  { name: "Steam", color: "#171a21", description: "Relates to the Steam platform." },
  { name: "Switch", color: "#e60012", description: "Relates to the Nintendo Switch platform." },
  { name: "Xbox", color: "#107c10", description: "Relates to the Xbox platform." },
  { name: "Claude as a platform", color: "#d77757", description: "Relates to running on or targeting Claude as a platform." },
  { name: "LLM", color: "#00a900", description: "Relates to large language model integration." },
  { name: "MCP", color: "#0bb800", description: "Relates to the Model Context Protocol." },
  { name: "Agents", color: "#16a900", description: "Relates to AI agents." },
  { name: "Skills and commands", color: "#0b9900", description: "Relates to skills and slash commands." },
  { name: "Not a bug", color: "#aaff8a", description: "Reported as a bug but is expected or correct behavior." },
  { name: "Needs followup", color: "#529400", description: "Awaiting follow-up information or action before progressing." },
  { name: "Partner", color: "#9fc400", description: "A business partner with a say in the project." },
  { name: "Customer", color: "#becd00", description: "A customer (an entity purchasing our products) with a say in the project." },
  { name: "Client", color: "#afbd00", description: "A client (an entity that has hired us or engaged our services) with a say in the project." },
  { name: "Employer", color: "#c1ba00", description: "An employer with a say in the project." },
  { name: "Employee", color: "#acd200", description: "An employee with a say in the project." },
  { name: "Chrome", color: "#4285f4", description: "Relates to the Google Chrome browser." },
  { name: "Firefox", color: "#ff7139", description: "Relates to the Mozilla Firefox browser." },
  { name: "Safari", color: "#0fb5ee", description: "Relates to the Apple Safari browser." },
  { name: "Edge", color: "#3ccbf4", description: "Relates to the Microsoft Edge browser." },
  { name: "Desktop", color: "#59c06b", description: "Relates to desktop devices." },
  { name: "Mobile", color: "#14763a", description: "Relates to mobile devices." },
  { name: "Build infrastructure", color: "#9ef43d", description: "Relates to build infrastructure and CI systems." },
  { name: "Static analysis", color: "#6affbe", description: "Relates to static analysis, linting, or type checking." },
  { name: "Status: Next sprint", color: "#001bc7", description: "Scheduled for the next sprint." },
  { name: "Needs information", color: "#428600", description: "Cannot proceed until more information is provided." },
  { name: "Unsolved", color: "#b1ff79", description: "Remains unsolved." },
  { name: "Size: tiny", color: "#5c3100", description: "A tiny amount of work." },
  { name: "Size: small", color: "#854700", description: "A small amount of work." },
  { name: "Size: medium", color: "#ad5c00", description: "A moderate amount of work." },
  { name: "Size: large", color: "#d67200", description: "A large amount of work." },
  { name: "Size: huge", color: "#ff8800", description: "A very large amount of work." },
  { name: "Size: unknown", color: "#331b00", description: "The amount of work has not yet been estimated." },
  { name: "Difficulty: unknown", color: "#5ac9ff", description: "The difficulty has not yet been assessed." },
  { name: "Reopened", color: "#00a7d9", description: "Was closed and has since been reopened." },
  { name: "Regressed", color: "#52c841", description: "A previously working behavior has regressed." },
  { name: "Unconfirmed", color: "#a29bfb", description: "Reported but not yet confirmed." },
  { name: "Big picture", color: "#d6d847", description: "Concerns high-level direction or strategy." },
  { name: "Breaking change", color: "#f33000", description: "Introduces a backward-incompatible change." },
  { name: "Security", color: "#e83f00", description: "Relates to a security concern or vulnerability." },
  { name: "Meta", color: "#15eee0", description: "Concerns the project's own administration rather than its code." },
  { name: "CI/CD", color: "#9aff2b", description: "Relates to continuous integration and deployment pipelines." },
  { name: "Website", color: "#e1a5a7", description: "Relates to the project's website." },
  { name: "Customer acquisition", color: "#ffe112", description: "A commerce issue about acquiring new customers." },
  { name: "Customer retention", color: "#fffb00", description: "A commerce issue about retaining existing customers." },
  { name: "Threat management", color: "#ffea00", description: "A commerce issue about identifying and managing competitive threats." },
  { name: "Business opportunity", color: "#ffd700", description: "A commerce issue: a potential market opportunity." },
  { name: "Business threat", color: "#fff412", description: "A commerce issue: competitive pressure or rivals in the marketplace." },
  { name: "Critical", color: "#a80f0f", description: "Severe impact; breaks core functionality or causes data loss." },
  { name: "Major", color: "#e8821e", description: "Significant impact on important functionality." },
  { name: "Moderate", color: "#e6c012", description: "Noticeable impact, but a reasonable workaround exists." },
  { name: "Minor", color: "#a0c63d", description: "Small impact with limited consequences." },
  { name: "Cosmetic", color: "#3cb44b", description: "Visual or polish issue with no functional impact." },
  { name: "Urgent", color: "#d55abe", description: "Requires immediate attention." },
  { name: "Trivial priority", color: "#c061b2", description: "Lowest priority; address only if convenient." },
  { name: "Medium priority", color: "#cc5dac", description: "Moderate priority; address in the normal course of work." },
  { name: "Stale", color: "#4ec044", description: "The issue is drifting without attention, falling between the cracks rather than by any decision." },
  { name: "Accessibility", color: "#7efdc1", description: "Relates to the accessibility (a11y) of the project." },
  { name: "Internationalization", color: "#57ff00", description: "Relates to supporting multiple languages and regions." },
  { name: "Localization", color: "#44ff00", description: "Relates to translating and adapting for a specific locale." },
  { name: "Bug is upstream", color: "#10afc3", description: "The defect originates in an upstream dependency, not this project." },
  { name: "Will deprecate", color: "#5ab834", description: "Slated to be deprecated in a future release." },
  { name: "Deprecated", color: "#52c92d", description: "Has been deprecated and may be removed." },
  { name: "Slop", color: "#64ecc5", description: "Used to reject AI-generated submissions that are nonsensical or otherwise unacceptable." },
  { name: "Important for integration", color: "#bbffff", description: "Important because it affects integration with other systems." },
  { name: "Socially important", color: "#b1eeff", description: "Important for social or community reasons." },
  { name: "Important for trust", color: "#a7ffff", description: "Important for maintaining user or stakeholder trust." },
  { name: "Fixed", color: "#f899ff", description: "The fix is complete; awaiting release or verification." },
  { name: "Verified", color: "#3fb4b2", description: "The fix or change has been verified." },
  { name: "Technical debt", color: "#73eeb8", description: "Accumulated shortcuts or compromises that need future cleanup." },
  { name: "Release blocker", color: "#10b1d8", description: "Must be resolved before the next release can ship." },
  { name: "Flaky", color: "#8d49ff", description: "An unreliable test that passes or fails inconsistently." },
  { name: "Status: Needs design", color: "#ff2b73", description: "Requires design input before implementation can begin." },
  { name: "License", color: "#00e872", description: "Relates to software licensing." },
  { name: "Privacy", color: "#00ef84", description: "Relates to user privacy or data protection." },
  { name: "Hotfix", color: "#f34e00", description: "An urgent out-of-cycle fix." },
  { name: "Sponsorship", color: "#b87333", description: "Relates to project sponsorship or funding." },
  { name: "PDF", color: "#ff3dde", description: "Relates to PDF documents or PDF output." },
  { name: "Fonts", color: "#c0a7ad", description: "Relates to font files or font handling." },
  { name: "Backend", color: "#feb4b0", description: "Concerns the backend or server-side code." },
  { name: "Fullstack", color: "#ff95a8", description: "Spans both the frontend and the backend." },
  { name: "Bare metal", color: "#3fa67e", description: "Relates to running directly on hardware with no OS or VM layer." },
  { name: "Uncertain", color: "#a0a8ec", description: "The situation or resolution is uncertain." },
  { name: "Out of scope", color: "#adff9b", description: "Determined to fall outside the project's intended scope." },
  { name: "Maintenance", color: "#d700b5", description: "Fixing broken software or configuration." },
  { name: "Cli", color: "#ed98b3", description: "Relates to the command-line interface." },
  { name: "Codegen", color: "#ff44ef", description: "Relates to code generation." },
  { name: "Language server", color: "#ff3dff", description: "Relates to a language server implementation." },
  { name: "Workflows", color: "#91ff4b", description: "Relates to automated workflows or workflow configuration." },
  { name: "Ahead of its time", color: "#b244c0", description: "A sound idea that is premature given current constraints." },
  { name: "Almost done", color: "#ff880d", description: "Nearly complete; only minor work remains." },
  { name: "Already available", color: "#bcff8c", description: "The requested capability already exists." },
  { name: "API", color: "#f6a6a7", description: "Relates to the project's public API." },
  { name: "Installer", color: "#ecacb7", description: "Relates to the installer or installation process." },
  { name: "Search", color: "#eca996", description: "Relates to search functionality." },
  { name: "Authentication", color: "#feb39c", description: "Relates to authentication, login, or credentials." },
  { name: "Community", color: "#a26a3f", description: "Relates to the project's community." },
  { name: "Do not merge", color: "#0096cf", description: "Must not be merged in its current state." },
  { name: "Merge ready", color: "#ff9800", description: "Approved and ready to be merged." },
  { name: "Miscellaneous", color: "#7454c0", description: "Does not fit any other category." },
  { name: "Needs translation", color: "#5100e0", description: "Requires translation work before completion." },
  { name: "Needs spec", color: "#4e14ea", description: "Requires a specification before work can begin." },
  { name: "Needs implementation", color: "#5402f2", description: "Specified or designed but not yet implemented." },
  { name: "Needs ui", color: "#600ce3", description: "Requires user-interface design or work." },
  { name: "Needs review", color: "#4013dd", description: "Awaiting review before it can progress." },
  { name: "Needs approval", color: "#5b7b00", description: "Awaiting approval before it can proceed." },
  { name: "Needs improvement", color: "#4502d3", description: "Acceptable but should be improved before completion." },
  { name: "Needs answers", color: "#497200", description: "Open questions must be answered before progressing." },
  { name: "Needs advice", color: "#5b6b00", description: "Needs advice or guidance before moving forward." },
  { name: "Needs feedback", color: "#538400", description: "Awaiting feedback before it can progress." },
  { name: "Needs rebase", color: "#5214d6", description: "The branch must be rebased before it can merge." },
  { name: "Needs splitting up", color: "#4003e8", description: "Too large; should be split into smaller pieces." },
  { name: "Needs external", color: "#00b7cd", description: "Blocked pending action from an external party." },
  { name: "Needs triage", color: "#9baefe", description: "Awaiting initial triage." },
  { name: "Status: Backlog", color: "#4b009a", description: "Queued in the backlog for future scheduling." },
  { name: "Status: In triage", color: "#4d0087", description: "Currently being triaged." },
  { name: "Status: Not planned", color: "#3e007d", description: "Acknowledged but not planned for any release." },
  { name: "Status: Cannot reproduce", color: "#2e0088", description: "A reproduction was provided, but following it does not reproduce the problem." },
  { name: "Status: Needs reproduction", color: "#3b0093", description: "No reproduction has been provided yet; one is needed before the issue can proceed." },
  { name: "Status: In roadmap", color: "#7d3f8f", description: "Accepted for implementation; not yet scheduled." },
  { name: "Status: In milestone", color: "#1028c2", description: "Scheduled against a specific release milestone." },
  { name: "Status: In sprint", color: "#763f7e", description: "In the current active batch of work." },
  { name: "Status: Assigned", color: "#0023b5", description: "Assigned to someone to work on." },
  { name: "Status: In design", color: "#ff2a86", description: "In the design phase." },
  { name: "Status: Underway", color: "#ff3d89", description: "Someone is actively working on it right now." },
  { name: "Status: In review", color: "#ff3e76", description: "Currently under review." },
  { name: "Status: Merged", color: "#b50500", description: "The change has been merged." },
  { name: "Status: Released", color: "#a21300", description: "The change has been deployed to production." },
  { name: "Status: Reverted", color: "#a30000", description: "Was deployed and then rolled back." },
  { name: "Status: Superseded", color: "#b41800", description: "Replaced by a later issue or change." },
  { name: "Blocks others", color: "#119fce", description: "Blocks other work from progressing." },
  { name: "Quality: very low", color: "#450c71", description: "Work assessed as very low quality." },
  { name: "Quality: low", color: "#4e187e", description: "Work assessed as low quality." },
  { name: "Quality: medium", color: "#58258a", description: "Work assessed as medium quality." },
  { name: "Quality: high", color: "#613197", description: "Work assessed as high quality." },
  { name: "Quality: very high", color: "#6b3da4", description: "Work assessed as very high quality." },
  { name: "Quality: unknown", color: "#3b0064", description: "Quality has not yet been assessed." },
  { name: "Effort: 1/5 - 1 person up to 1/2 day", color: "#000080", description: "Roughly one person for up to half a day." },
  { name: "Effort: 2/5 - 1 person up to 3 days", color: "#37056f", description: "Roughly one person for up to three days." },
  { name: "Effort: 3/5 - up to 3 people 1 week", color: "#6e0a5e", description: "Up to three people for about a week." },
  { name: "Effort: 4/5 - plan and divide; up to 1 month", color: "#a50f4d", description: "Needs planning and division of labour; up to a month of work." },
  { name: "Effort: 5/5 - plan and divide; enormous", color: "#dc143c", description: "Needs planning and division of labour; an enormous undertaking." },
  { name: "Effort estimate missing", color: "#6e0a5e", description: "No effort estimate has been recorded." },
  { name: "Modernize", color: "#e900af", description: "Updating outdated code, dependencies, or practices to modern standards." },
  { name: "SEO", color: "#fff488", description: "Relates to search-engine optimization and discoverability." },
  { name: "GEO", color: "#fffd99", description: "Relates to generative-engine optimization for AI answer engines." },
  { name: "Youtube", color: "#ff0000", description: "Relates to the project's presence on YouTube." },
  { name: "Facebook", color: "#1877f2", description: "Relates to the project's presence on Facebook." },
  { name: "Tiktok", color: "#fe2c55", description: "Relates to the project's presence on TikTok." },
  { name: "Linkedin", color: "#0a66c2", description: "Relates to the project's presence on LinkedIn." },
  { name: "Reddit", color: "#ff4500", description: "Relates to the project's presence on Reddit." },
  { name: "Backlog", color: "#44bc34", description: "Intentionally remaindered: a deliberate decision to shelve, not reject or act on now." }
];
